### ISSUE TITLE
Error: Unrecognized extension: ut_pex

### ISSUE THREAD

**Issue by Gank** [fisch0920/ut_pex#8]
I'm playing around with latest version of bittorrent_protocol (2.1.3) and ut_pex (1.1.0) and got the following error:

```bash
Error: Unrecognized extension: ut_pex
    at Wire.extended (/Users/gank/torrent-discovery/node_modules/bittorrent-protocol/index.js:383:11)
    at ut_pex._sendMessage (/Users/gank/torrent-discovery/node_modules/ut_pex/index.js:160:16)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.unrefdHandle (timers.js:312:14)
```

Any breaking change in the latest versions?

**Comment by feross** [comment]
@Gank Not that I know of. If you post a complete code example, I can be of more help.
